#!/bin/sh
set -e

echo "Running go fmt..."
go fmt ./...

echo "Running go vet..."
go vet ./...

echo "Running tests..."
go test ./...

echo "Running golangci-lint..."
C:/Users/SAndriyanich/golangci-lint/golangci-lint.exe run ./...
